# This is a basic workflow that is manually triggered

name: Build Pubs

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker://pandoc/extra:latest
        with:
          args: >-  # allows you to break string into multiple lines
            pages/publications/lab-publications.bib
            -s 
            -f biblatex 
            -t markdown 
            -o pages/publications/lab-pubs.txt
      - uses: actions/upload-artifact@v2
        with:
          name: lab-pubs
          path: pages/publications/lab-pubs.txt
            
      

