# This is a basic workflow that is manually triggered

name: Build Pubs

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: pandoc
       working-directory: pages/publications
       uses: docker://pandoc/extra:latest
        with:
          args: >-  # allows you to break string into multiple lines
            lab-publications.bib
            -s 
            -f biblatex 
            -t markdown 
            -o lab-pubs.txt
      

