# This is a basic workflow that is manually triggered

name: Build Pubs

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker://pandoc/extra:latest
        with:
          args: >-  # allows you to break string into multiple lines
            pages/publications/lab-publications.bib
            -s 
            -f biblatex 
            -t markdown 
            -o pages/publications/lab-pubs.txt
      - name: GIT commit and push docs
        env: 
          CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
          CI_COMMIT_AUTHOR: Continuous Integration
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "amunn@gmx.com"
          git add pages/publications
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push
      - uses: docker://pandoc/extra:latest
        with:
          args: >-
             --citeproc 
             --csl pages/publications/apa-cv 
             pages/publications/lab-pubs.txt 
             -o pages/publications/tmp-bib.txt
      - run: >- 
          cat pages/publications/bibliography-header.txt pages/publications/tmp-bib.txt 
          > pages/publications/lab-publications.md; rm pages/publications/lab-pubs.txt
      - name: GIT commit and push again
        env: 
          CI_COMMIT_MESSAGE: Updated publications
          CI_COMMIT_AUTHOR: Continuous Integration
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "amunn@gmx.com"
          git add pages/publications
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push
          


            
      

